added if sucess() to gcloud cli

diff --git a/capture-blob/action.yaml b/capture-blob/action.yaml
--- a/capture-blob/action.yaml
+++ b/capture-blob/action.yaml
@@ -75,6 +75,7 @@ runs:
         id_token_include_email: true
         workload_identity_provider: 'projects/68661080711/locations/global/workloadIdentityPools/fianu-github-actions/providers/github'
         service_account: ${{ inputs.fianu-service-account }}
+        export_environment_variables: true
 
     # Google Cloud CLI Installation
     - name: Google Cloud CLI Installation
@@ -127,18 +128,22 @@ runs:
         fi
         
         # Capture the Generated Bundle with Fianu
-        
-        echo <<-EOF
+
+        cat <<<EOF
         ### Capturing Blob Evidence with Fianu CLI:
         
         ```bash
-          fianu capture evidence \
-            --input bundle.json \
-            --type "blob" \
-            --source "${{ inputs.evidence-source }}" \
-            --resource-uri "${{ inputs.evidence-uri }}" \
-            ${opts}
+        fianu capture evidence \
+          --type "blob" \
+          --source "${{ inputs.evidence-source }}" \
+          --resource-uri "${{ inputs.evidence-uri }}" \
+          ${opts}
         ```
         EOF >> $GITHUB_STEP_SUMMARY
         
         fianu capture evidence --input bundle.json --type "blob" --source "${{ inputs.evidence-source }}" --resource-uri "${{ inputs.evidence-uri }}" ${opts}
+        
+        if [ $? -ne 0 ]; then 
+          echo "error: failed to capture evidence with Fianu CLI." >&2
+          exit 1
+        fi
